sudo: required

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

after_success:
  - ls
  - cp CNAME output/ ; cp .gitignore output/ ; cp _config.yml output/ ; cp LICENSE output/ ; cp -R images output/
  - cd output
  - git init
  - git config user.name "${GT_USER_NAME}"
  - git config user.email "{GT_EMAIL}"
  - git add . ; git commit -m "Pushing converted documents."
  - git push --force --quiet "https://${GT_TOKEN}@${GT_URL}" doc